# Generated by Django 4.2.2 on 2023-06-13 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnfemaPorject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('meta_first_published_at', models.DateTimeField(verbose_name='date published')),
                ('client', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('brand_main_color', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Last Updated')),
            ],
        ),
    ]
