# Generated by Django 4.2.2 on 2023-06-14 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anfema_projects', '0002_alter_anfemaporject_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anfemaporject',
            old_name='brand_main_color',
            new_name='brand_main_colour',
        ),
    ]
