# Generated by Django 4.2.2 on 2023-06-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anfema_projects', '0003_rename_brand_main_color_anfemaporject_brand_main_colour'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnfemaPorject',
            new_name='AnfemaProject',
        ),
    ]
